server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/volunteer?useSSL=false&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: 1998918Jyc
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jyc.volunteer.entity